### ISSUE TITLE
Support hashtags with Umlauts

### ISSUE THREAD

**Issue by LukasRos** [LukasRos/phpADNSite#3]

**Comment by LukasRos** [comment]
@farmio: It converts hashtags with umlauts correctly into links but when I click on it I'm not getting a list of posts with that hashtag. Does that work for you?

**Comment by farmio** [comment]
yes it works as expected with (currently latest) safari and chrome for osx in my test-instance with php 5.4

**Comment by LukasRos** [comment]
Ok, was a problem with my test environment then.
