### ISSUE TITLE
Hashtag image-caption conflict

### ISSUE THREAD

**Issue by farmio** [LukasRos/phpADNSite#6]
Hashtag-links are overwritten by Image-links if the image-caption and the hashtag-name is the same.

**Comment by LukasRos** [comment]
@farmio If you want me to fix it give me a sample post where this problem occurs.

**Comment by farmio** [comment]
i have found a Post where it occour without hashtags: http://farmous.net/post/62524241
and one with hashtags and without hashtags http://farmous.net/post/62193404
